service: payment-events-processor

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: develop

functions:
  ReceiveMessage:
    handler: src/receiveMessage/handler/index.handler
    environment:
      MESSAGE_TOPIC_URL: !Ref PaymentEventsTopic
      MESSAGE_QUEUE_URL: !Ref PaymentEventsQueue
      DYNAMODB_TABLE: !Ref PaymentEventsTable
    iamRoleStatementsName: ${self:service}-${self:provider.stage}-ReceiveMessageRole
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sns:Publish
        Resource:
          - !Ref PaymentEventsTopic
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource:
          - !GetAtt PaymentEventsQueue.Arn
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:Query
          - dynamodb:Scan
        Resource:
          - !GetAtt PaymentEventsTable.Arn
    events:
      - sns:
          arn: !Ref PaymentEventsTopic
          topicName: payment-events-topic
    timeout: 30
    memorySize: 256

  PublishMessage:
    handler: src/publishMessage/handler/index.handler
    environment:
      MESSAGE_TOPIC_URL: !Ref PaymentEventsTopic
      MESSAGE_QUEUE_URL: !Ref PaymentEventsQueue
      DYNAMODB_TABLE: !Ref PaymentEventsTable
    iamRoleStatementsName: ${self:service}-${self:provider.stage}-PublishMessageRole
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
          - sqs:ReceiveMessage
          - sqs:DeleteMessage
          - sqs:GetQueueAttributes
        Resource:
          - !GetAtt PaymentEventsQueue.Arn
      - Effect: Allow
        Action:
          - sns:Publish
        Resource:
          - !Ref PaymentEventsTopic
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:Query
          - dynamodb:Scan
        Resource:
          - !GetAtt PaymentEventsTable.Arn
    events:
      - sqs:
          arn: !GetAtt PaymentEventsQueue.Arn
          batchSize: 1
    timeout: 30
    memorySize: 256

resources:
  - ${file(resource/sns.yml)}
  - ${file(resource/sqs.yml)}
  - ${file(resource/dynamodb.yml)}
