service: payment-events-processor

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: develop

functions:
  ReceiveMessage:
    handler: src/receiveMessage/handler/index.handler
    environment:
      MESSAGE_TOPIC_URL: !Ref PaymentEventsTopic
      DYNAMODB_TABLE: !Ref PaymentEventsTable
    iamRoleStatementsName: ${self:service}-${self:provider.stage}-ReceiveMessageRole
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sns:Publish
        Resource:
          - !Ref PaymentEventsTopic
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:Query
          - dynamodb:Scan
        Resource:
          - !GetAtt PaymentEventsTable.Arn
    events:
      - sns:
          arn: !Ref PaymentEventsTopic
          topicName: payment-events-topic
    timeout: 30
    memorySize: 256

  PublishMessage:
    handler: src/publishMessage/handler/index.handler
    environment:
      MESSAGE_QUEUE_URL: !Ref PaymentEventsQueue
      DYNAMODB_TABLE: !Ref PaymentEventsTable
    iamRoleStatementsName: ${self:service}-${self:provider.stage}-PublishMessageRole
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
          - sqs:ReceiveMessage
          - sqs:DeleteMessage
          - sqs:GetQueueAttributes
        Resource:
          - !GetAtt PaymentEventsQueue.Arn
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:Query
          - dynamodb:Scan
        Resource:
          - !GetAtt PaymentEventsTable.Arn
    events:
      - sqs:
          arn: !GetAtt PaymentEventsQueue.Arn
          batchSize: 1
    timeout: 30
    memorySize: 256

resources:
  Resources:
    PaymentEventsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-${self:provider.stage}-PaymentEventsTopic
        DisplayName: Payment Events SNS Topic
        Subscription:
          - Endpoint: devmartinese@gmail.com
            Protocol: email

    PaymentEventsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-PaymentEventsQueue
        VisibilityTimeoutSeconds: 30
        MessageRetentionPeriod: 1209600
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt PaymentEventsDLQ.Arn
          maxReceiveCount: 3

    PaymentEventsDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-PaymentEventsDLQ
        MessageRetentionPeriod: 1209600

    PaymentEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-PaymentEvents
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: timestamp-index
            KeySchema:
              - AttributeName: timestamp
                KeyType: HASH
            Projection:
              ProjectionType: ALL
