Resources:
  PaymentEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-PaymentEventsQueue
      VisibilityTimeoutSeconds: 30
      MessageRetentionPeriod: 1209600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PaymentEventsDLQ.Arn
        maxReceiveCount: 3

  PaymentEventsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-PaymentEventsDLQ
      MessageRetentionPeriod: 1209600 